### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by JagravNaik** [20lives/FrontendMastersDownloader#10]
Login failed: 429: You have reached maximum request limit.

When trying to download a course after another one has finished, this is the response.

node version
v14.6.0

npm version
6.14.7

**Comment by 20lives** [comment]
This seems to be a wide problem in the app, I will post a solution soon.

**Comment by 20lives** [comment]
I have pushed an update, successful logins will be saved for future use so you won't be blocked when using multiple times.
