### ISSUE TITLE
not working 18.08

### ISSUE THREAD

**Issue by YossefVexAfeka** [20lives/FrontendMastersDownloader#11]
may be they changeg servers?
log:
` download Introduction to Node.js? (Y/n) Yes
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn youtube-dl ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn youtube-dl',
  path: 'youtube-dl',
  spawnargs: [
    '-o./Introduction to Node.js//1. Course Overview.mp4',
    'https://player.vimeo.com/external/303305854.m3u8?s=f2a7cc45db18c832ef6559d182f8af1c649aec85&oauth2_token_id=1034790340'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontendmasters-downloader@0.2.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontendmasters-downloader@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/neobit/.npm/_logs/2020-08-18T12_21_10_800Z-debug.log
`

**Comment by 20lives** [comment]
quick guess is that you don't have [youtube-dl](https://ytdl-org.github.io/youtube-dl/index.html) installed or it's not on you **PATH**
