### ISSUE TITLE
Cannot find ffmpeg

### ISSUE THREAD

**Issue by lyqht** [20lives/FrontendMastersDownloader#12]
After selecting a course search result, it will throw an unhandled error event of
```
Error: Cannot find ffmpeg
```

Using windows 10

**Comment by 20lives** [comment]
Hi, as the README state, you will need FFMPEG.
you can download it from [ffmpeg.org](https://ffmpeg.org) and make sure the binary is accessible from your path, or just place it in the directory you run the tool.

**Comment by lyqht** [comment]
oh yeah it was the path problem! thanks!
