### ISSUE TITLE
cannot find ffmpeg

### ISSUE THREAD

**Issue by kareemegy** [20lives/FrontendMastersDownloader#16]
when I start using  the package it gives me this weird error every time I try to download  a course and here is a picture  from the CMD

[https://ibb.co/r5KNLfx](url)

and thank you for your hard word, really appreciated

**Comment by koff75** [comment]
You need to install FFMPEG separately like this below on your terminal:
`brew install ffmpeg`
It uses brew for macOS but you can find the equivalent depending on your OS.

**Comment by erdkse** [comment]
I created a [PR](https://github.com/20lives/FrontendMastersDownloader/pull/17) for this issue. You dont need to do;
```
brew install ffmpeg
```

**Comment by 20lives** [comment]
Hi all, sorry for not responding sooner,
This issue came up a few times before: look at #12

**Comment by kareemegy** [comment]
thanks, guys it works now
