### ISSUE TITLE
Fed-hasher

### ISSUE THREAD

**Issue by miraklez** [20lives/FrontendMastersDownloader#23]
https://github.com/20lives/FrontendMastersDownloader/blob/0771f4f7a6dde13f951cc68b8b84b08908b66866/src/constants.js#L2

Can u give us more informations about how fed-hasher works ?
And why using a service for that ? 
Thanks in advance

**Comment by 20lives** [comment]
Hi, sorry for the late response,
this is a part of the authentication process, given a timestamp, the service will generate a hash that the API will be looking for to successfully log it.
