### ISSUE TITLE
does it support dowloading new m3u8 and ts video?

### ISSUE THREAD

**Issue by zhengdai** [20lives/FrontendMastersDownloader#26]
I want to know does it support dowloading new m3u8 and ts video

**Comment by 20lives** [comment]
I don't understand your question, it supports all video courses available in frontendmasters.

**Comment by zhengdai** [comment]
![image](https://user-images.githubusercontent.com/4944849/100820237-c168ce80-3488-11eb-8af6-4f04750842b6.png)
the programs is null

**Comment by 20lives** [comment]
do you have ffmpeg and ffprobe installed ? which versions ? are they in the path?

**Comment by zhengdai** [comment]
![image](https://user-images.githubusercontent.com/4944849/100991831-67eac780-358e-11eb-9fa7-b8668cff0e1b.png)
![image](https://user-images.githubusercontent.com/4944849/100991883-75a04d00-358e-11eb-93d0-9da2e32ecd87.png)

**Comment by 20lives** [comment]
I can't reproduce this, is this only for this one course or a courses?

**Comment by zhengdai** [comment]
> I can't reproduce this, is this only for this one course or a courses?

I know，it's the great wall because I'm in China.
