### ISSUE TITLE
Course not found

### ISSUE THREAD

**Issue by mirshahnewaz** [20lives/FrontendMastersDownloader#3]
Hi there,
it just keeps saying course not found although the course is there and my credentials are right?
Is this a known issue?

Many thanks
Mir

**Comment by Adarsh777** [comment]
I also got the same problem, **course not found** although my credentials are right too.

**Comment by 20lives** [comment]
As I answered before, the script wasn't maintained for over 2 years, I will find time to make it work again soon.

**Comment by 20lives** [comment]
@mirshahnewaz @Adarsh777 a new working version is available
