### ISSUE TITLE
Login failed: not authorized

### ISSUE THREAD

**Issue by bhuvanmehra** [20lives/FrontendMastersDownloader#38]
Thanks for the awesome library. It was working for me for a long time.
However, since last week, I have started getting the following error - 
I have confirmed my credentials and they work.
Would be awesome to see this repo in action again.

Login failed: 401: not authorized
Login failed: 429: You have reached maximum request limit.

**Comment by 20lives** [comment]
Please read #35 
tldr; you can make it work again but you might lose your account.
