### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Adarsh777** [20lives/FrontendMastersDownloader#4]
Hello,

When I'm running `npx frontendmasters-downloader` getting this below image attached error,

![image](https://user-images.githubusercontent.com/20425116/83128504-279b2000-a0f9-11ea-823a-2038cdc7580c.png)

Also tried running `npm run start` then getting this error 

![image](https://user-images.githubusercontent.com/20425116/83128669-5d400900-a0f9-11ea-970f-a229a2c6b75f.png)

Thanks

**Comment by 20lives** [comment]
what is your node version? run `node --version` to find out.
I am using es modules which is only available on recent node versions  (13+ I think)

**Comment by Adarsh777** [comment]
> what is your node version? run `node --version` to find out.
> I am using es modules which is only available on recent node versions (13+ I think)

v12.4

**Comment by Adarsh777** [comment]
I have updated my node version to v14.3.0 and then it shows me this,

![image](https://user-images.githubusercontent.com/20425116/83140262-6e921100-a10b-11ea-8921-976f3c301d10.png)

**Comment by 20lives** [comment]
Npm package wasn't aligned with the git version, should work now.

**Comment by Adarsh777** [comment]
> Npm package wasn't aligned with the git version, should work now.

Thanks, It is working now. 
It might be better if you add delay between downloads, which will remove the account banned problem.
